export const foodMock = [
  {
    id: 90423,
    name: "Shrimp",
    price: 2.79,
    description: "Shrimp is a seafood that lives in the sea.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=1",
  },
  {
    id: 90424,
    name: "Salmon",
    price: 9.99,
    description: "Salmon is a popular fish known for its rich flavor.",
    unit: "lb",
    shelfLife: "3 days",
    image: "https://picsum.photos/1000?random=2",
  },
  {
    id: 90425,
    name: "Tuna",
    price: 7.49,
    description: "Fresh tuna steak, great for grilling or searing.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=3",
  },
  {
    id: 90426,
    name: "Lobster",
    price: 14.99,
    description: "Live lobster, a delicacy from the ocean.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=4",
  },
  {
    id: 90427,
    name: "Crab Legs",
    price: 12.99,
    description: "Snow crab legs, perfect for seafood lovers.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=5",
  },
  {
    id: 90428,
    name: "Mussels",
    price: 5.49,
    description: "Fresh mussels, ideal for seafood pasta dishes.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=6",
  },
  {
    id: 90429,
    name: "Clams",
    price: 6.99,
    description: "Live clams, excellent for clam chowder.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=7",
  },
  {
    id: 90430,
    name: "Oysters",
    price: 8.99,
    description: "Fresh oysters, perfect for raw or grilled preparations.",
    unit: "dozen",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=8",
  },
  {
    id: 90431,
    name: "Swordfish",
    price: 10.99,
    description: "Swordfish steak, a firm and flavorful fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=9",
  },
  {
    id: 90432,
    name: "Scallops",
    price: 11.99,
    description: "Large sea scallops, great for searing.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=10",
  },
  {
    id: 90433,
    name: "Red Snapper",
    price: 13.49,
    description: "Red snapper fillet, a mild and flaky fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=11",
  },
  {
    id: 90434,
    name: "Halibut",
    price: 12.99,
    description: "Halibut steak, known for its delicate flavor.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=12",
  },
  {
    id: 90435,
    name: "Crawfish",
    price: 7.99,
    description: "Live crawfish, a Louisiana favorite.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=13",
  },
  {
    id: 90436,
    name: "Octopus",
    price: 9.99,
    description: "Fresh octopus, ideal for Mediterranean dishes.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=14",
  },
  {
    id: 90437,
    name: "Squid",
    price: 6.49,
    description: "Whole squid, perfect for calamari recipes.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=15",
  },
  {
    id: 90438,
    name: "Anchovies",
    price: 3.99,
    description: "Salted anchovies, a flavorful addition to various dishes.",
    unit: "lb",
    shelfLife: "6 months",
    image: "https://picsum.photos/1000?random=16",
  },
  {
    id: 90439,
    name: "Haddock",
    price: 8.49,
    description: "Haddock fillet, a versatile white fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=17",
  },
  {
    id: 90440,
    name: "Eel",
    price: 10.99,
    description: "Fresh eel, a delicacy in some cuisines.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=18",
  },
  {
    id: 90441,
    name: "Sardines",
    price: 4.49,
    description: "Canned sardines, a convenient source of Omega-3.",
    unit: "can",
    shelfLife: "1 year",
    image: "https://picsum.photos/1000?random=19",
  },
  {
    id: 90442,
    name: "Caviar",
    price: 99.99,
    description: "Premium sturgeon caviar, a luxury delicacy.",
    unit: "oz",
    shelfLife: "3 months",
    image: "https://picsum.photos/1000?random=20",
  },
  {
    id: 90443,
    name: "Tilapia",
    price: 5.99,
    description: "Tilapia fillet, a mild and affordable white fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=21",
  },
];

export const cartMock = [
  {
    id: 90423,
    name: "Shrimp",
    price: 2.79,
    description: "Shrimp is a seafood that lives in the sea.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=1",
    amount: 10,
  },

  {
    id: 90429,
    name: "Clams",
    price: 6.99,
    description: "Live clams, excellent for clam chowder.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=7",
    amount: 6,
  },
  {
    id: 90430,
    name: "Oysters",
    price: 8.99,
    description: "Fresh oysters, perfect for raw or grilled preparations.",
    unit: "dozen",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=8",
    amount: 4,
  },
  {
    id: 90431,
    name: "Swordfish",
    price: 10.99,
    description: "Swordfish steak, a firm and flavorful fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=9",
    amount: 12,
  },

  {
    id: 90434,
    name: "Halibut",
    price: 12.99,
    description: "Halibut steak, known for its delicate flavor.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=12",
    amount: 5,
  },
  {
    id: 90435,
    name: "Crawfish",
    price: 7.99,
    description: "Live crawfish, a Louisiana favorite.",
    unit: "lb",
    shelfLife: "1 day",
    image: "https://picsum.photos/1000?random=13",
    amount: 1,
  },
  {
    id: 90436,
    name: "Octopus",
    price: 9.99,
    description: "Fresh octopus, ideal for Mediterranean dishes.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=14",
    amount: 2,
  },
  {
    id: 90437,
    name: "Squid",
    price: 6.49,
    description: "Whole squid, perfect for calamari recipes.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=15",
    amount: 1,
  },

  {
    id: 90440,
    name: "Eel",
    price: 10.99,
    description: "Fresh eel, a delicacy in some cuisines.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=18",
    amount: 3,
  },
  {
    id: 90441,
    name: "Sardines",
    price: 4.49,
    description: "Canned sardines, a convenient source of Omega-3.",
    unit: "can",
    shelfLife: "1 year",
    image: "https://picsum.photos/1000?random=19",
    amount: 4,
  },
  {
    id: 90442,
    name: "Caviar",
    price: 99.99,
    description: "Premium sturgeon caviar, a luxury delicacy.",
    unit: "oz",
    shelfLife: "3 months",
    image: "https://picsum.photos/1000?random=20",
    amount: 9,
  },
  {
    id: 90443,
    name: "Tilapia",
    price: 5.99,
    description: "Tilapia fillet, a mild and affordable white fish.",
    unit: "lb",
    shelfLife: "2 days",
    image: "https://picsum.photos/1000?random=21",
    amount: 9,
  },
];
